name: Generate Snake Game

on:
  schedule: # Run at midnight every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake game from commits
        uses: Platane/snk@v2
        with:
          github_user_name: Icey-Python
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Add the generated GIF to the repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Generate Snake game"
          git push
